<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SmartHome.Test" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SmartHome.DL\SmartHome.DL.csproj" />
	  <ProjectReference Include="..\SmartHome.Models\SmartHome.Models.csproj" />
	</ItemGroup>



</Project>
